# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iShopList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Auth'

pod 'SwipeCellKit'
pod "KRProgressHUD"

  # Pods for iShopList

  target 'iShopListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iShopListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
